version: "3"

services:
    # mysql:
    #     image: mysql:5.7
    #     ports:
    #         - "3306:3306"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_ROOT_PASSWORD: secret
    #         MYSQL_DATABASE: OPENSOURCE-API
    #         MYSQL_USER: root
    #         MYSQL_PASSWORD: secret
    #     volumes:
    #         - ./docker/mysql:/docker-entrypoint-initdb.d

    mongodb:
        image: mvertes/alpine-mongo
        ports:
            - "27017:27017"

    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always

    postgres:
        image: postgres
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: OPENSOURCE-API
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./docker/postgres/initdb.sh:/docker-entrypoint-initdb.d/init.sh
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

volumes:
    ? postgres-data
